version: '3'
services:
  odoo:
    build: .  # This tells Docker to use your Dockerfile
    image: odoo:17.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "0.0.0.0:8080:8069"
    volumes:
      - data:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons  # Add this line
    environment:
      - ADDONS_PATH=/mnt/extra-addons  # Add this line
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
